version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=customer_feedback_db
      - JWT_SECRET_KEY=dev-jwt-secret-key-12345
      - FLASK_SECRET_KEY=dev-secret
    depends_on:
      - db
    volumes:
      - ./interninfos:/app
    command: python app.py

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customer_feedback_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./interninfos/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
